<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
<style>
input[type="radio"]:not(:checked) ~ .hidden {display: none;}
input[type="radio"]:checked ~ .hidden {display: inherit;}
</style>
</head>
<body>
<?php echo '<p>PHP '.phpversion().'</p>'; ?>
<h4>The <a href="https://php.net/manual/en/function.password-hash.php">password_hash()</a> function in PHP.</h4>
<?php if (version_compare(PHP_VERSION, '5.5.0') >= 0) { ?>
<?php if (constant("PASSWORD_ARGON2I") == 2) { ?> <!-- Check if Argon2 is available. -->
<form action="" method="post">
    <span>Select password algorithm</span><br>
    <input type="radio" name="algo" value="argon"> Argon2<br>
    <input type="radio" name="algo" value="bcrypt"> bcrypt<br><br>
    <div class="hidden">
        <span>Enter text to hash</span><br>
        <input type="text" name="text" autocomplete="off">
        <input type="submit" name="input" value="hash">
    </div>
</form>
<?php } else { ?>
<form action="" method="post">
    <p>(Only bcrypt is available for PHP 5.5.0 to 7.2.0 and XAMPP builds.)</p>
    <span>Enter text to hash</span><br>
    <input type="text" name="text" autocomplete="off">
    <input type="submit" name="input" value="hash">
</form>
<?php } ?>
<?php
if (!empty($_POST['input'])) {
    $algo=$_POST['algo'];
    $text=$_POST['text'];
    if ($algo == argon) {
        $hash = password_hash($text, PASSWORD_ARGON2I);
    } elseif ($algo == bcrypt) {
        $hash = password_hash($text, PASSWORD_BCRYPT);
    } else $hash = password_hash($text, PASSWORD_DEFAULT); // Same as PASSWORD_BCRYPT since it is the default.
    echo '<pre style="font-size: 1.1em;">'.$hash.'</pre>';
}
?>
<h4>The <a href="https://php.net/manual/en/function.password-verify.php">password_verify()</a> function in PHP.</h4>
<?php if (!empty($hash)) { ?>
<form action="" method="post">
    <span>Enter text to verify the hash</span><br>
    <input type="hidden" name="hash" value="<?php echo $hash; ?>" autocomplete="off">
    <input type="text" name="guess" autocomplete="off">
    <input type="submit" name="execute" value="verify">
</form>
<?php
} elseif (!empty($_POST['execute'])) {
    $hash=$_POST['hash'];
    $guess=$_POST['guess'];
    if (password_verify($guess, $hash)) {
        echo '<pre style="font-size: 1.1em; color: green;">Valid!</pre>';
        echo '<pre style="font-size: 1.1em;">"'.$guess.'" is the password.</pre>';
    } else {
        echo '<pre style="font-size: 1.1em; color: red;">Invalid!</pre>';
        echo '<pre style="font-size: 1.1em;">"'.$guess.'" is not the password.</pre>';
    }
} else echo 'Waiting for hash...';
?>
<?php } else echo '<p>PHP before 5.5.0 cannot use either password_hash() or password_verify().</p>' ?>
</body>
</html>
